server:
  servlet:
    context-path: /hello
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.huangbei.testproject.Entity
  config-location: classpath:mybatis-config.xml

logging:
  config: classpath:logback-boot.xml
  level:
      com.huangbei.testproject: INFO
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
